### ISSUE TITLE
Environment configuration error

### ISSUE THREAD

**Issue by Taylor-Liu** [google-research/dads#1]
Hi, Archit, thanks for sharing your code.

I had some trouble when configuring the environment,

(1) What's the version of mujoco you used in your project? In README.md, the version of mujoco is 150, but in env.yml, it require "mujoco-py==2.0.2.5". 

(2) The package "tf-nightly==1.15.0.dev20190819" in env.yml could not be installed. I checked the site https://pypi.org/project/tf-nightly/#history, but I can't find the version of 1.15.0.dev20190819.

**Comment by architsharma97** [comment]
(1) I did the experiments with MuJoCo 150, but should work with MuJoCo 200 too.
(2) The environment and code tnow work with the latest tf-nightly.
