### ISSUE TITLE
Config for Humanoid environment.

### ISSUE THREAD

**Issue by LemonATsu** [google-research/dads#3]
Hi Archit, 

Thanks for sharing the code of this great work.
I would like to ask if you can provide the config file of off-policy DADS for Humanoid environment. It seems to me that the configuration for off-policy DADS would be a bit different from the numbers specified in the paper. It would be helpful if we can have access to it. Thanks!

**Comment by architsharma97** [comment]
Hi,
I have added both the on-policy and off-policy configuration files. Hope it helps!

**Comment by LemonATsu** [comment]
This is great. Thanks! Just one additional question: is there any guideline in balancing the agent and the dynamic model training steps (e.g., what metrics to look at)?

**Comment by architsharma97** [comment]
The training steps for dynamics models is decided based on dimensionality / size of the state-space (so smaller state-space, fewer steps).

The agent steps are decided somewhat by how much data is being added to the buffer in every iteration. We want to take as many steps possible without overfitting. I have no strong metrics or guidelines but the initial intuition was to take about 4 steps for every step collected (in expectation of course).
