### ISSUE TITLE
Use of skill_discriminator.py

### ISSUE THREAD

**Issue by maridia** [google-research/dads#5]
Hi,

Is the SkilDiscriminator class used at all in this project?  I can't find where it is ever called.  

Thanks.

**Comment by architsharma97** [comment]
You can use it to construct different reward function, but it is not necessary for reproducing DADS.

**Comment by maridia** [comment]
Hi Archit,

Thanks for your quick reply.  From looking at the reward function, I'm guessing you mostly used it for reproducing the DIAYN results?

**Comment by architsharma97** [comment]
Yes! But, there would be subtle differences from the open-sourced version of DIAYN if you choose to use the skill-discriminator from this codebase.
